# 8-Aug-26

# Exam Task on Pandas (Data Cleaning)

In [2]:
# Part 1 — Inspect & Understand the Dataset
# Q1. Load the dataset

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\customer_analytics.csv")
print(df.head())

   Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55         44033       111350.85          772             3
1       101001  32        215546       254378.37          374             8
2       101069  23        226403       159975.42          668            12
3       101968  66         87824        295741.6          315            14
4       100530  67         31570       242423.78          370             4

        City  Segment Channel            Join_Date Active Risk_Level  \
0  Bangalore      SME   Agent  2022-08-15 00:00:00    Yes        Low
1      Delhi   Retail   Agent  2025-01-11 00:00:00    Yes       High
2    Chennai  Premium   Agent  2024-08-01 00:00:00     No     Medium
3     Mumbai  Premium   Agent  2021-05-15 00:00:00    Yes       High
4  bangalore   Retail   Agent  2026-02-03 00:00:00     No       High

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7

In [3]:
# Q2. Inspect the end of the dataset

# Display the last 15 rows

print(df.tail(15))

      Customer_ID            Age Annual_Income Account_Balance Credit_Score  \
2025       100088             51        214004       173779.91          686
2026       101483  not_available        117573       261905.82          657
2027       100331             54        123511       280896.35          388
2028       101239             31        125500       189174.28          846
2029       100467            NaN        101619       279182.04          392
2030       100122             41        201611        40736.71          507
2031       101639             61        128850        266135.8          840
2032       101045             33         88037       129948.93          449
2033       101725             43        122756        36633.45          487
2034       101096             18        189232       235131.72          306
2035       101131             42         88530       153490.72          677
2036       101295             31        205738        270989.4          392
2037       100861             25        211994       160507.65          737
2038       101460             64         30105        32117.15          794
2039       101127             55        248332       274980.99          783

      Tenure_Years       City    Segment Channel            Join_Date Active  \
2025             6       Pune    Premium  Branch  2022-04-22 00:00:00    Yes
2026             2       Pune        NaN  Branch  2022-07-02 00:00:00    Yes
2027             5       Pune    Premium  Mobile  2024-09-11 00:00:00     No
2028            11      Delhi  Corporate   Agent  2022-04-08 00:00:00    Yes
2029             3  Bangalore     Retail  Mobile  2023-07-26 00:00:00    Yes
2030            15  Bangalore        SME   Agent  2024-11-03 00:00:00    Yes
2031             9    Kolkata        SME  Mobile  2026-01-15 00:00:00    Yes
2032             8     Mumbai    Premium  Mobile  2022-11-30 00:00:00    Yes
2033             8       Pune        NaN  Mobile  2021-07-04 00:00:00     No
2034            10  hyderabad        SME  Mobile  2025-09-10 00:00:00     No
2035            12  Hyderabad     Retail   Agent  2021-07-10 00:00:00     No
2036             8     Mumbai  Corporate   Agent  2025-07-05 00:00:00    Yes
2037             8    Kolkata     Retail  Online  2022-10-17 00:00:00    Yes
2038             8  Bangalore     Retail   Agent  2023-08-26 00:00:00     No
2039             6    Chennai     Retail  Branch                  NaN    Yes

     Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
2025     Medium       39764.87           85                 4.9
2026     Medium       39559.16            7                 1.9
2027       High            NaN           48                 6.7
2028        Low       22161.09          102                 8.5
2029       High       37316.48          100                 7.3
2030       High       18815.18           58                 7.2
2031        Low       34300.44           83                 5.0
2032       High  not_available          147                 9.7
2033       High       10165.71           14                 6.4
2034       High       27227.44           85                 5.9
2035     Medium        8455.42          119                 8.6
2036       High       34087.69          134                 2.6
2037        Low       26518.74           87                 1.3
2038        Low       20943.11          107                 9.3
2039        Low       48511.32          119                 3.1

In [4]:
# Q3. Random inspection

#Display 10 random records

print(df.sample(10))

      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
1127       100604  69         98297        87008.76          424
1232       101449  53         32999       282459.87          557
868        100844  66         35526       296297.88          691
409        101849  34        225696       277276.28          655
1978       100021  70        130595       135179.11          521
922        100143  72        177499       291222.65          478
1798       101435  68        191597       213039.79          410
497        101044  71         95017       181623.53          593
435        100951  26        193757       226078.39          503
542        100746  48        211898             NaN          433

      Tenure_Years       City    Segment Channel            Join_Date Active  \
1127             0      Delhi     Retail  Branch  2022-11-12 00:00:00    Yes
1232             2    Kolkata     Retail   Agent  2025-09-01 00:00:00      0
868             12       Pune  Corporate  Mobile  2025-09-17 00:00:00    Yes
409             13     mumbai  Corporate  Online  2025-10-18 00:00:00    Yes
1978            11    Chennai  Corporate  Mobile  2022-03-24 00:00:00    Yes
922             13       Pune    Premium  Branch  2024-09-04 00:00:00    Yes
1798             0    Kolkata        SME  Online  2021-11-21 00:00:00    Yes
497              1    Kolkata        SME  Online  2024-08-19 00:00:00    Yes
435             12  Hyderabad     Retail   Agent  2022-03-10 00:00:00    Yes
542              5      Delhi        SME  Online  2025-06-14 00:00:00      N

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
1127       High      17043.66           35                 2.0
1232     Medium       6892.25           88                 6.7
868      Medium      45383.75          131                 6.3
409      Medium           NaN          124                 3.1
1978       High       4344.78          124                 4.5
922        High      43628.01           19                10.0
1798       High       9377.99           67                 7.0
497      Medium      16530.56           99                 3.6
435        High      25701.13          abc                 2.5
542        High         34799           24                 3.4

In [5]:
# Q4. Dataset audit

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   str
 2   Annual_Income       1933 non-null   str
 3   Account_Balance     1912 non-null   str
 4   Credit_Score        2036 non-null   str
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   str
 7   Segment             1935 non-null   str
 8   Channel             2040 non-null   str
 9   Join_Date           1938 non-null   str
 10  Active              1981 non-null   str
 11  Risk_Level          2040 non-null   str
 12  Monthly_Spend       1931 non-null   str
 13  Transactions        2038 non-null   str
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), str(12)
memory usage: 239.2 KB
None

In [6]:
print("Rows:", df.shape[1])
print("Columns:", df.shape[1])

Rows: 15
Columns: 15

In [7]:
# Q5. Missing-value audit

# Calculate the number of missing values in every column

print(df.isnull().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [8]:
# using isna():

print(df.isna().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [9]:
# verify the result using both:

print(df.isnull().sum() == df.isna().sum())

Customer_ID           True
Age                   True
Annual_Income         True
Account_Balance       True
Credit_Score          True
Tenure_Years          True
City                  True
Segment               True
Channel               True
Join_Date             True
Active                True
Risk_Level            True
Monthly_Spend         True
Transactions          True
Satisfaction_Score    True
dtype: bool

In [10]:
# Part 2 — Detect & Fix Data Quality Problems
# Q6. Duplicate investigation
# Find how many duplicate rows exist
# Do not remove them yet

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 40

In [11]:
# Q7. Remove duplicates
# Remove all duplicate records and store the cleaned result back into df

df = df.drop_duplicates()
print("Duplicates after cleaning:",df.duplicated().sum())

Duplicates after cleaning: 0

In [12]:
# Q8. Numeric column investigation
# Select only numeric columns.

print(df.select_dtypes(include="Object").columns)

TypeError: data type 'Object' not understood

In [ ]:
# Q9. Fix Age
# The Age column contains: Valid numbers,Missing values,Invalid text

df["Age"] = pd.to_numeric(df["Age"],errors="coerce")
median_age = df["Age"].median()
df["Age"] = df["Age"].fillna(median_age)

print(df["Age"])
print(df["Age"].dtype)

In [ ]:
# Q10. Fix Annual Income

df["Annual_Income"] = pd.to_numeric(df["Annual_Income"],errors="coerce")
median_income = df["Annual_Income"].median()
df["Annual_Income"] = df["Annual_Income"].fillna(median_income).astype(float)

In [ ]:
df["Annual_Income"]

In [ ]:
median_income

In [ ]:
df["Annual_Income"]

In [ ]:
# Part 3 — Numerical Cleaning
# Q11. Clean Account Balance

df["Account_Balance"] = pd.to_numeric(df["Account_Balance"],errors="coerce")
mean_balance = df["Account_Balance"].mean()
df["Account_Balance"] = df["Account_Balance"].fillna(mean_balance)

print(df["Account_Balance"])
print(df["Account_Balance"].dtype)

In [ ]:
# Q12. Clean Credit Score

df["Credit_Score"] = pd.to_numeric(df["Credit_Score"],errors="coerce")
median_credit = df["Credit_Score"].median()
df["Credit_Score"] = df["Credit_Score"].fillna(median_credit)
df["Credit_Score"] = df["Credit_Score"].astype(int)

print(df["Credit_Score"])
print(df["Credit_Score"].dtype)

In [ ]:
# Q13. Clean Monthly Spend

df["Monthly_Spend"] = pd.to_numeric(df["Monthly_Spend"],errors="coerce")
median_spend = df["Monthly_Spend"].median()
df["Monthly_Spend"] = df["Monthly_Spend"].fillna(median_spend)
df["Monthly_Spend"] = df["Monthly_Spend"].astype(float)

print(df["Monthly_Spend"])
print(df["Monthly_Spend"].dtype)

In [ ]:
# Q14. Clean Transactions

df["Transactions"] = pd.to_numeric(df["Transactions"],errors="coerce")
median_transactions = df["Transactions"].median()
df["Transactions"] = df["Transactions"].fillna(median_transactions)
df["Transactions"] = df["Transactions"].astype(int)

print(df["Transactions"])
print(df["Transactions"].dtype)

In [ ]:
# Q15. Clean Satisfaction Score

df["Satisfaction_Score"] = pd.to_numeric(df["Satisfaction_Score"],errors="coerce")
mean_satisfaction = df["Satisfaction_Score"].mean()
df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(mean_satisfaction)
df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

print(df["Satisfaction_Score"])
print(df["Satisfaction_Score"].dtype)

In [ ]:
# Part 4 — Date Cleaning
# Q16. Investigate Join_Date

print(df["Join_Date"].head(20))
print("\nMissing dates:")
print(df["Join_Date"].isnull().sum())
print("\nUnique date formats/values:")
print(df["Join_Date"].unique())

In [ ]:
# Q17. Convert Join_Date
# Convert Join_Date into a proper Pandas datetime column.

df["Join_Date"] = pd.to_datetime(df["Join_Date"],errors="coerce")
print(df["Join_Date"])
print(df["Join_Date"].dtype)

In [ ]:
# Q18. Handle missing dates

print("Missing dates:",df["Join_Date"].isna().sum())

In [ ]:
# Part 5 — Categorical Cleaning
# Q19. Clean City

df["City"] = df["City"].replace({"mumbai":"Mumbai"})
print(df["City"].value_counts())

In [ ]:
# Q20. Analyze Segment

print(df["Segment"].value_counts())
print("\nMissing values.")
print(df["Segment"].isnull().sum())
print(df["Segment"].value_counts().reindex(["Retail","SME","Corporate","Premium"]))

In [ ]:
# Q21. Clean Active

df["Active"] = df["Active"].replace({
    "Y": "YES",
    "y": "YES",
    "YES": "YES",
    "1": "YES",
    1: "YES",
    "N": "NO",
    "n": "NO",
    "NO": "NO",
    "0": "NO",
    0: "No"
})
print(df["Active"].value_counts())

In [ ]:
# Q22. Clean Risk_Level

print(df["Risk_Level"].value_counts())
print("\nMissing values:")
print(df["Risk_Level"].isnull().sum())

In [ ]:
# Verify whether missing values exist.

most_common_risk = df["Risk_Level"].mode()[0]

df["Risk_Level"] = df["Risk_Level"].fillna(most_common_risk)

print("\nFinal Risk Level Distribution:")
print(df["Risk_Level"].value_counts())

In [ ]:
# Part 6 — Column Transformation
# Q23. Rename columns

df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend"
})

print(df.columns)

In [ ]:
# Q24. Add a prefix

df = df.add_prefix("Customer_")
print(df.columns)

In [ ]:
# Q25. Remove unnecessary column

clean_df = df.drop(columns=["Customer_Customer_ID"])

print(clean_df.head())

In [ ]:
# Part 7 — Create New Columns
# Q26. Create Annual Income in Lakhs

clean_df["Income_Lakhs"] = clean_df["Customer_AnnualIncome"] / 100000

print(clean_df.head(10))

In [ ]:
# Q27. Create Monthly Income

clean_df["MonthlyIncome"] = clean_df["Customer_AnnualIncome"] / 12

clean_df["Income_After_Spending"] = (
    clean_df["MonthlyIncome"] - clean_df["Customer_MonthlySpend"]
)

print(clean_df.head())

In [ ]:
# Q28. Create Balance-to-Income Ratio

clean_df["Balance_Income_Ratio"] = (
    clean_df["Customer_AccountBalance"] /
    clean_df["Customer_AnnualIncome"].replace(0, pd.NA)
)

print(clean_df.head(10))

In [ ]:
# Part 8 — Final Real-World Cleaning Challenge
# Q29. Prepare the ML-ready dataset

# Load the dataset

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\customer_analytics.csv")
print(df.head())

# Inspect

print(df.head(10))
print(df.tail(10))
print(df.sample(10))

In [ ]:
# 3. Inspect the last 10 rows.
print(df.info())

In [ ]:
# 4. Inspect 10 random records.

print("\nMissing values:")
print(df.isnull().sum())
print(df.isna().sum())

In [ ]:
# 5. Run info().

print("\nDuplicates:")
print(df.duplicated().sum())

In [ ]:
# 6. Check missing values.

df = df.drop_duplicates()

In [ ]:
df

In [ ]:
# 7. Check duplicates.

# Age
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"] = df["Age"].astype(int)

# Annual Income
df["Annual_Income"] = pd.to_numeric(
    df["Annual_Income"], errors="coerce")

df["Annual_Income"] = df["Annual_Income"].fillna(
    df["Annual_Income"].median())

df["Annual_Income"] = df["Annual_Income"].astype(float)

# Account Balance
df["Account_Balance"] = pd.to_numeric(
    df["Account_Balance"], errors="coerce")

df["Account_Balance"] = df["Account_Balance"].fillna(
    df["Account_Balance"].mean())

df["Account_Balance"] = df["Account_Balance"].astype(float)

# Credit Score
df["Credit_Score"] = pd.to_numeric(
    df["Credit_Score"], errors="coerce")

df["Credit_Score"] = df["Credit_Score"].fillna(
    df["Credit_Score"].median())

df["Credit_Score"] = df["Credit_Score"].astype(int)

# Monthly Spend
df["Monthly_Spend"] = pd.to_numeric(
    df["Monthly_Spend"], errors="coerce")

df["Monthly_Spend"] = df["Monthly_Spend"].fillna(
    df["Monthly_Spend"].median())

df["Monthly_Spend"] = df["Monthly_Spend"].astype(float)

# Transactions
df["Transactions"] = pd.to_numeric(
    df["Transactions"], errors="coerce")

df["Transactions"] = df["Transactions"].fillna(
    df["Transactions"].median())

df["Transactions"] = df["Transactions"].astype(int)

# Satisfaction Score
df["Satisfaction_Score"] = pd.to_numeric(
    df["Satisfaction_Score"], errors="coerce")

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(
    df["Satisfaction_Score"].mean())

df["Satisfaction_Score"] = df["Satisfaction_Score"].astype(float)

In [ ]:
df["Satisfaction_Score"]

In [ ]:
df["Transactions"]

In [ ]:
df["Monthly_Spend"]

In [ ]:
df["Credit_Score"]

In [ ]:
df["Account_Balance"]

In [ ]:
df["Annual_Income"]

In [ ]:
# 8. Remove duplicates.

df["Join_Date"] = pd.to_datetime(
    df["Join_Date"], errors="coerce")

In [ ]:
df["Join_Date"]

In [ ]:
# 9. Clean all numeric columns.

# City
df["City"] = df["City"].str.title()

# Segment
df["Segment"] = df["Segment"].fillna(
    df["Segment"].mode()[0])


# Channel
df["Channel"] = df["Channel"].str.title()
df["Channel"] = df["Channel"].fillna(
    df["Channel"].mode()[0])


# Active
df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "y": "Yes",
    "YES": "Yes",
    "1": "Yes",
    1: "Yes",
    "N": "No",
    "n": "No",
    "NO": "No",
    "0": "No",
    0: "No"
})

df["Active"] = df["Active"].fillna(
    df["Active"].mode()[0])


# Risk Level
df["Risk_Level"] = df["Risk_Level"].fillna(
    df["Risk_Level"].mode()[0])

In [ ]:
df["City"]

In [ ]:
df["Segment"]

In [ ]:
df["Channel"]

In [ ]:
df["Active"]

In [ ]:
df["Risk_Level"]

In [ ]:
# 10. Convert invalid numeric values to missing.

df = df.rename(columns={
    "Customer_ID": "CustomerID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})

In [ ]:
df

In [ ]:
# 11. Fill numerical missing values appropriately.

df = df.drop(columns=["CustomerID"])

In [ ]:
df

In [ ]:
# 12. Convert Join_Date to datetime.

df["Income_Lakhs"] = df["AnnualIncome"] / 100000

df["MonthlyIncome"] = df["AnnualIncome"] / 12

df["Income_After_Spending"] = (
    df["MonthlyIncome"] - df["MonthlySpend"])


df["Balance_Income_Ratio"] = (
    df["AccountBalance"] /
    df["AnnualIncome"].replace(0, pd.NA))

In [ ]:
df["Income_Lakhs"]

In [ ]:
df["MonthlyIncome"]

In [ ]:
df["Income_After_Spending"]

In [ ]:
df["Balance_Income_Ratio"]

In [ ]:
# 13. Handle invalid dates.

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

In [ ]:
# 14. Standardize categorical values.

print("\nHEAD:")
print(df.head())

print("\nTAIL:")
print(df.tail())

print("\nSAMPLE:")
print(df.sample(10))

print("\nINFO:")
print(df.info())

print("\nDESCRIBE:")
print(df.describe())

print("\nACTIVE DISTRIBUTION:")
print(df["Active"].value_counts())

print("\nRISK LEVEL DISTRIBUTION:")
print(df["RiskLevel"].value_counts())

print("\nSEGMENT DISTRIBUTION:")
print(df["Segment"].value_counts())

In [14]:
# 15. Clean the binary Active column.

df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    1: "Yes",
    "1": "Yes",

    "N": "No",
    "NO": "No",
    "no": "No",
    0: "No",
    "0": "No"
})

active_mode = df["Active"].value_counts().index[0]

df["Active"] = df["Active"].fillna(active_mode)
df["Active"]

0       Yes
1       Yes
2        No
3       Yes
4        No
       ...
2035     No
2036    Yes
2037    Yes
2038     No
2039    Yes
Name: Active, Length: 2000, dtype: str

In [15]:
# 16. Rename the columns.

df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})
df

,Customer_ID,Age,AnnualIncome,AccountBalance,CreditScore,Tenure,City,Segment,Channel,CustomerJoinDate,Active,RiskLevel,MonthlySpend,Transactions,SatisfactionScore
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [17]:
# 17. Remove unnecessary columns.

df = df.add_prefix("Customer_")
df

,Customer_Customer_Customer_ID,Customer_Customer_Age,Customer_Customer_AnnualIncome,Customer_Customer_AccountBalance,Customer_Customer_CreditScore,Customer_Customer_Tenure,Customer_Customer_City,Customer_Customer_Segment,Customer_Customer_Channel,Customer_Customer_CustomerJoinDate,Customer_Customer_Active,Customer_Customer_RiskLevel,Customer_Customer_MonthlySpend,Customer_Customer_Transactions,Customer_Customer_SatisfactionScore
0,101317,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,101001,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,101069,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,101968,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,100530,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,101131,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,101295,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,100861,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,101460,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,101127,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [19]:
# 18. Verify the final datatypes.

df = df.drop(columns=["Customer_Customer_Customer_ID"])
df

,Customer_Customer_Age,Customer_Customer_AnnualIncome,Customer_Customer_AccountBalance,Customer_Customer_CreditScore,Customer_Customer_Tenure,Customer_Customer_City,Customer_Customer_Segment,Customer_Customer_Channel,Customer_Customer_CustomerJoinDate,Customer_Customer_Active,Customer_Customer_RiskLevel,Customer_Customer_MonthlySpend,Customer_Customer_Transactions,Customer_Customer_SatisfactionScore
0,55,44033,111350.85,772,3,Bangalore,SME,Agent,2022-08-15 00:00:00,Yes,Low,23066.19,135,3.1
1,32,215546,254378.37,374,8,Delhi,Retail,Agent,2025-01-11 00:00:00,Yes,High,NaN,106,8.2
2,23,226403,159975.42,668,12,Chennai,Premium,Agent,2024-08-01 00:00:00,No,Medium,28536.34,146,6.3
3,66,87824,295741.6,315,14,Mumbai,Premium,Agent,2021-05-15 00:00:00,Yes,High,12869.71,115,9.7
4,67,31570,242423.78,370,4,bangalore,Retail,Agent,2026-02-03 00:00:00,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42,88530,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10 00:00:00,No,Medium,8455.42,119,8.6
2036,31,205738,270989.4,392,8,Mumbai,Corporate,Agent,2025-07-05 00:00:00,Yes,High,34087.69,134,2.6
2037,25,211994,160507.65,737,8,Kolkata,Retail,Online,2022-10-17 00:00:00,Yes,Low,26518.74,87,1.3
2038,64,30105,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26 00:00:00,No,Low,20943.11,107,9.3
2039,55,248332,274980.99,783,6,Chennai,Retail,Branch,NaN,Yes,Low,48511.32,119,3.1

In [21]:
# 19. Generate descriptive statistics.

df["Income_Lakhs"] = df["Customer_Customer_AnnualIncome"] / 100000

df["MonthlyIncome"] = df["Customer_Customer_AnnualIncome"] / 12

df["Income_After_Spending"] = (
    df["MonthlyIncome"] - df["Customer_MonthlySpend"]
)


# Avoid division by zero
df["Balance_Income_Ratio"] = (
    df["Customer_AccountBalance"] /
    df["Customer_Customer_AnnualIncome"].replace(0, pd.NA)
)
df["MonthlyIncome"]

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [23]:
# 20. Check categorical distributions.

print("\nFINAL DATASET INFORMATION")
df.info()


print("\nFINAL DUPLICATES")
print(df.duplicated().sum())


print("\nFINAL MISSING VALUES")
print(df.isnull().sum())


print("\nNUMERIC COLUMNS")
print(df.select_dtypes(include="number").columns)


print("\nDESCRIPTIVE STATISTICS")
print(df.describe())


print("\nACTIVE DISTRIBUTION")
print(df["Active"].value_counts())


print("\nCITY DISTRIBUTION")
print(df["Customer_City"].value_counts())


print("\nSEGMENT DISTRIBUTION")
print(df["Customer_Segment"].value_counts())


print("\nCHANNEL DISTRIBUTION")
print(df["Customer_Channel"].value_counts())


print("\nRISK LEVEL DISTRIBUTION")
print(df["Customer_RiskLevel"].value_counts())


# Final display
print("\nFIRST 10 ROWS")
print(df.head(10))

print("\nLAST 10 ROWS")
print(df.tail(10))

print("\nRANDOM 10 ROWS")
print(df.sample(10))

FINAL DATASET INFORMATION
<class 'pandas.DataFrame'>
Index: 2000 entries, 0 to 2039
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Customer_Customer_Age                1918 non-null   str
 1   Customer_Customer_AnnualIncome       1893 non-null   str
 2   Customer_Customer_AccountBalance     1875 non-null   str
 3   Customer_Customer_CreditScore        1996 non-null   str
 4   Customer_Customer_Tenure             2000 non-null   int64
 5   Customer_Customer_City               1920 non-null   str
 6   Customer_Customer_Segment            1900 non-null   str
 7   Customer_Customer_Channel            2000 non-null   str
 8   Customer_Customer_CustomerJoinDate   1900 non-null   str
 9   Customer_Customer_Active             2000 non-null   str
 10  Customer_Customer_RiskLevel          2000 non-null   str
 11  Customer_Customer_MonthlySpend       1893 non-null   str
 12  Customer_Customer_Transactions       1998 non-null   str
 13  Customer_Customer_SatisfactionScore  1920 non-null   float64
dtypes: float64(1), int64(1), str(12)
memory usage: 234.4 KB

FINAL DUPLICATES
0

FINAL MISSING VALUES
Customer_Customer_Age                   82
Customer_Customer_AnnualIncome         107
Customer_Customer_AccountBalance       125
Customer_Customer_CreditScore            4
Customer_Customer_Tenure                 0
Customer_Customer_City                  80
Customer_Customer_Segment              100
Customer_Customer_Channel                0
Customer_Customer_CustomerJoinDate     100
Customer_Customer_Active                 0
Customer_Customer_RiskLevel              0
Customer_Customer_MonthlySpend         107
Customer_Customer_Transactions           2
Customer_Customer_SatisfactionScore     80
dtype: int64

NUMERIC COLUMNS
Index(['Customer_Customer_Tenure', 'Customer_Customer_SatisfactionScore'], dtype='str')

DESCRIPTIVE STATISTICS
       Customer_Customer_Tenure  Customer_Customer_SatisfactionScore
count               2000.000000                          1920.000000
mean                   7.574000                             5.605417
std                    4.610548                             2.579632
min                    0.000000                             1.000000
25%                    4.000000                             3.400000
50%                    8.000000                             5.700000
75%                   12.000000                             7.800000
max                   15.000000                            10.000000

ACTIVE DISTRIBUTION

KeyError: 'Active'

In [24]:
# Q30 — Ultimate Pandas Cleaning Project

import pandas as pd

# step 1:
df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\customer_analytics.csv")

In [25]:
# STEP 2 — INSPECT

print(df.head(10))

print(df.tail(10))

print(df.sample(10))

df.info()

   Customer_ID Age Annual_Income Account_Balance Credit_Score  Tenure_Years  \
0       101317  55         44033       111350.85          772             3
1       101001  32        215546       254378.37          374             8
2       101069  23        226403       159975.42          668            12
3       101968  66         87824        295741.6          315            14
4       100530  67         31570       242423.78          370             4
5       101334  68         37087       180084.44          738             1
6       100415  47         67229        99629.81          464             4
7       100983  65           NaN        61030.94          554            15
8       100417  63        153267       221707.97          508             5
9       101472  42       missing        41126.84          556             3

        City    Segment Channel            Join_Date Active Risk_Level  \
0  Bangalore        SME   Agent  2022-08-15 00:00:00    Yes        Low
1      Delhi     Retail   Agent  2025-01-11 00:00:00    Yes       High
2    Chennai    Premium   Agent  2024-08-01 00:00:00     No     Medium
3     Mumbai    Premium   Agent  2021-05-15 00:00:00    Yes       High
4  bangalore     Retail   Agent  2026-02-03 00:00:00     No       High
5    Chennai    Premium   Agent  2023-06-04 00:00:00    Yes        Low
6    Chennai     Retail  Online  2024-01-16 00:00:00    Yes       High
7    Kolkata        SME   Agent  2024-06-26 00:00:00    Yes     Medium
8  Hyderabad    Premium  Mobile  2025-03-12 00:00:00    Yes       High
9    Kolkata  Corporate  Mobile  2021-10-07 00:00:00    Yes     Medium

  Monthly_Spend Transactions  Satisfaction_Score
0      23066.19          135                 3.1
1           NaN          106                 8.2
2      28536.34          146                 6.3
3      12869.71          115                 9.7
4      34163.02           94                 3.7
5      15121.16            6                 8.5
6      17655.61           31                 2.8
7       1720.85          139                 9.7
8      38043.07           76                 7.1
9      11472.36          124                 9.1
      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
2030       100122  41        201611        40736.71          507
2031       101639  61        128850        266135.8          840
2032       101045  33         88037       129948.93          449
2033       101725  43        122756        36633.45          487
2034       101096  18        189232       235131.72          306
2035       101131  42         88530       153490.72          677
2036       101295  31        205738        270989.4          392
2037       100861  25        211994       160507.65          737
2038       101460  64         30105        32117.15          794
2039       101127  55        248332       274980.99          783

      Tenure_Years       City    Segment Channel            Join_Date Active  \
2030            15  Bangalore        SME   Agent  2024-11-03 00:00:00    Yes
2031             9    Kolkata        SME  Mobile  2026-01-15 00:00:00    Yes
2032             8     Mumbai    Premium  Mobile  2022-11-30 00:00:00    Yes
2033             8       Pune        NaN  Mobile  2021-07-04 00:00:00     No
2034            10  hyderabad        SME  Mobile  2025-09-10 00:00:00     No
2035            12  Hyderabad     Retail   Agent  2021-07-10 00:00:00     No
2036             8     Mumbai  Corporate   Agent  2025-07-05 00:00:00    Yes
2037             8    Kolkata     Retail  Online  2022-10-17 00:00:00    Yes
2038             8  Bangalore     Retail   Agent  2023-08-26 00:00:00     No
2039             6    Chennai     Retail  Branch                  NaN    Yes

     Risk_Level  Monthly_Spend Transactions  Satisfaction_Score
2030       High       18815.18           58                 7.2
2031        Low       34300.44           83                 5.0
2032       High  not_available          147                 9.7
2033       High       10165.71           14                 6.4
2034       High       27227.44           85                 5.9
2035     Medium        8455.42          119                 8.6
2036       High       34087.69          134                 2.6
2037        Low       26518.74           87                 1.3
2038        Low       20943.11          107                 9.3
2039        Low       48511.32          119                 3.1
      Customer_ID Age Annual_Income Account_Balance Credit_Score  \
17         100351  53        108186        31442.42          314
45         100101  33        169059       228572.05          639
328        101661  62       unknown         83967.8          634
613        101560  51         43474        13212.11          835
1515       100370  50         25661             NaN          821
761        100775  54        213856       169097.99          429
1891       101514  66        170361        43292.76          672
1820       101644  61         86001        39150.38          636
35         100325  66        169701             NaN          429
1636       101808  42        164251       201854.14          428

      Tenure_Years       City    Segment Channel            Join_Date Active  \
17               0  Hyderabad  Corporate  Mobile  2022-05-25 00:00:00    NaN
45              15       Pune     Retail  Mobile  2024-10-04 00:00:00    Yes
328             13    Chennai    Premium  Online  2025-10-14 00:00:00    yes
613              2        NaN    Premium  Online  2023-03-26 00:00:00     No
1515            11     Mumbai     Retail  Branch  2021-07-20 00:00:00    Yes
761              9        NaN  Corporate  Mobile  2025-04-23 00:00:00    NaN
1891            15     Mumbai     Retail  Mobile                  NaN    Yes
1820             2      Delhi  Corporate  Branch  2024-10-19 00:00:00    Yes
35               9     Mumbai  Corporate  Branch  2023-08-27 00:00:00     No
1636             4      Delhi    Premium   Agent  2023-04-17 00:00:00    Yes

     Risk_Level Monthly_Spend Transactions  Satisfaction_Score
17         High      24056.68          121                 9.2
45       Medium           NaN          148                 6.1
328      Medium       7390.23           55                 5.5
613        High      40385.31           82                 6.8
1515        Low      36902.99      missing                 1.0
761        High        673.79           78                 NaN
1891     Medium      39634.31           91                 8.8
1820     Medium      27870.87           13                 7.4
35         High      17572.01          128                 3.9
1636       High      20597.62           91                 4.2
<class 'pandas.DataFrame'>
RangeIndex: 2040 entries, 0 to 2039
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         2040 non-null   int64
 1   Age                 1957 non-null   str
 2   Annual_Income       1933 non-null   str
 3   Account_Balance     1912 non-null   str
 4   Credit_Score        2036 non-null   str
 5   Tenure_Years        2040 non-null   int64
 6   City                1959 non-null   str
 7   Segment             1935 non-null   str
 8   Channel             2040 non-null   str
 9   Join_Date           1938 non-null   str
 10  Active              1981 non-null   str
 11  Risk_Level          2040 non-null   str
 12  Monthly_Spend       1931 non-null   str
 13  Transactions        2038 non-null   str
 14  Satisfaction_Score  1955 non-null   float64
dtypes: float64(1), int64(2), str(12)
memory usage: 239.2 KB

In [26]:
# STEP 3 — MISSING VALUE ANALYSIS

print(df.isnull().sum())

print(df.isna().sum())

Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64
Customer_ID             0
Age                    83
Annual_Income         107
Account_Balance       128
Credit_Score            4
Tenure_Years            0
City                   81
Segment               105
Channel                 0
Join_Date             102
Active                 59
Risk_Level              0
Monthly_Spend         109
Transactions            2
Satisfaction_Score     85
dtype: int64

In [27]:
# STEP 4 — DUPLICATES

print("Duplicates:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after cleaning:",
      df.duplicated().sum())

Duplicates: 40
Duplicates after cleaning: 0

In [29]:
# STEP 5 — NUMERIC CLEANING

# Age
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Age"] = df["Age"].fillna(df["Age"].median())


# Annual Income
df["Annual_Income"] = pd.to_numeric(
    df["Annual_Income"],
    errors="coerce"
)

df["Annual_Income"] = df["Annual_Income"].fillna(
    df["Annual_Income"].median()
)

df["Annual_Income"] = df["Annual_Income"].astype(float)


# Account Balance
df["Account_Balance"] = pd.to_numeric(
    df["Account_Balance"],
    errors="coerce"
)

df["Account_Balance"] = df["Account_Balance"].fillna(
    df["Account_Balance"].mean()
)


# Credit Score
df["Credit_Score"] = pd.to_numeric(
    df["Credit_Score"],
    errors="coerce"
)

df["Credit_Score"] = df["Credit_Score"].fillna(
    df["Credit_Score"].median()
)

df["Credit_Score"] = df["Credit_Score"].astype(int)


# Monthly Spend
df["Monthly_Spend"] = pd.to_numeric(
    df["Monthly_Spend"],
    errors="coerce"
)

df["Monthly_Spend"] = df["Monthly_Spend"].fillna(
    df["Monthly_Spend"].median()
)


# Transactions
df["Transactions"] = pd.to_numeric(
    df["Transactions"],
    errors="coerce"
)

df["Transactions"] = df["Transactions"].fillna(
    df["Transactions"].median()
)

df["Transactions"] = df["Transactions"].astype(int)


# Satisfaction Score
df["Satisfaction_Score"] = pd.to_numeric(
    df["Satisfaction_Score"],
    errors="coerce"
)

df["Satisfaction_Score"] = df["Satisfaction_Score"].fillna(
    df["Satisfaction_Score"].mean()
)

df["Satisfaction_Score"] = df[
    "Satisfaction_Score"
].astype(float)
df["Age"]
df["Annual_Income"]
df["Account_Balance"]
df["Credit_Score"]
df["Monthly_Spend"]
df["Transactions"]
df["Satisfaction_Score"]

0       3.1
1       8.2
2       6.3
3       9.7
4       3.7
       ...
2035    8.6
2036    2.6
2037    1.3
2038    9.3
2039    3.1
Name: Satisfaction_Score, Length: 2000, dtype: float64

In [31]:
# STEP 6 — DATE CLEANING

df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce"
)

valid_dates = df["Join_Date"].dropna().sort_values()

median_date = valid_dates.iloc[len(valid_dates) // 2]

df["Join_Date"] = df["Join_Date"].fillna(median_date)
df["Join_Date"]

0      2022-08-15
1      2025-01-11
2      2024-08-01
3      2021-05-15
4      2026-02-03
          ...
2035   2021-07-10
2036   2025-07-05
2037   2022-10-17
2038   2023-08-26
2039   2023-08-24
Name: Join_Date, Length: 2000, dtype: datetime64[us]

In [33]:
# STEP 7 — CATEGORICAL CLEANING

# City
df["City"] = df["City"].replace({
    "mumbai": "Mumbai",
    "MUMBAI": "Mumbai",
    "delhi": "Delhi",
    "DELHI": "Delhi",
    "bangalore": "Bangalore",
    "BANGALORE": "Bangalore",
    "hyderabad": "Hyderabad",
    "HYDERABAD": "Hyderabad",
    "chennai": "Chennai",
    "CHENNAI": "Chennai"
})


# Segment
df["Segment"] = df["Segment"].replace({
    "retail": "Retail",
    "RETAIL": "Retail",
    "sme": "SME",
    "SME": "SME",
    "corporate": "Corporate",
    "CORPORATE": "Corporate",
    "premium": "Premium",
    "PREMIUM": "Premium"
})

df["Segment"] = df["Segment"].fillna(
    df["Segment"].value_counts().index[0]
)


# Channel
df["Channel"] = df["Channel"].replace({
    "online": "Online",
    "ONLINE": "Online",
    "branch": "Branch",
    "BRANCH": "Branch",
    "mobile": "Mobile",
    "MOBILE": "Mobile"
})

df["Channel"] = df["Channel"].fillna(
    df["Channel"].value_counts().index[0]
)


# Active
df["Active"] = df["Active"].replace({
    "Y": "Yes",
    "YES": "Yes",
    "yes": "Yes",
    "1": "Yes",
    1: "Yes",

    "N": "No",
    "NO": "No",
    "no": "No",
    "0": "No",
    0: "No"
})

df["Active"] = df["Active"].fillna(
    df["Active"].value_counts().index[0]
)


# Risk Level
df["Risk_Level"] = df["Risk_Level"].replace({
    "high": "High",
    "HIGH": "High",
    "medium": "Medium",
    "MEDIUM": "Medium",
    "low": "Low",
    "LOW": "Low"
})

df["Risk_Level"] = df["Risk_Level"].fillna(
    df["Risk_Level"].value_counts().index[0]
)
df["Risk_Level"]

0          Low
1         High
2       Medium
3         High
4         High
         ...
2035    Medium
2036      High
2037       Low
2038       Low
2039       Low
Name: Risk_Level, Length: 2000, dtype: str

In [37]:
# STEP 8 — COLUMN TRANSFORMATION

df = df.rename(columns={
    "Customer_ID": "Customer_ID",
    "Annual_Income": "AnnualIncome",
    "Account_Balance": "AccountBalance",
    "Credit_Score": "CreditScore",
    "Tenure_Years": "Tenure",
    "Join_Date": "CustomerJoinDate",
    "Risk_Level": "RiskLevel",
    "Monthly_Spend": "MonthlySpend",
    "Satisfaction_Score": "SatisfactionScore"
})
df

,Customer_Customer_Customer_Age,Customer_Customer_Customer_AnnualIncome,Customer_Customer_Customer_AccountBalance,Customer_Customer_Customer_CreditScore,Customer_Customer_Customer_Tenure,Customer_Customer_Customer_City,Customer_Customer_Customer_Segment,Customer_Customer_Customer_Channel,Customer_Customer_Customer_CustomerJoinDate,Customer_Customer_Customer_Active,Customer_Customer_Customer_RiskLevel,Customer_Customer_Customer_MonthlySpend,Customer_Customer_Customer_Transactions,Customer_Customer_Customer_SatisfactionScore
0,55.0,44033.0,111350.85,772,3,Bangalore,SME,Agent,2022-08-15,Yes,Low,23066.19,135,3.1
1,32.0,215546.0,254378.37,374,8,Delhi,Retail,Agent,2025-01-11,Yes,High,24625.17,106,8.2
2,23.0,226403.0,159975.42,668,12,Chennai,Premium,Agent,2024-08-01,No,Medium,28536.34,146,6.3
3,66.0,87824.0,295741.60,315,14,Mumbai,Premium,Agent,2021-05-15,Yes,High,12869.71,115,9.7
4,67.0,31570.0,242423.78,370,4,Bangalore,Retail,Agent,2026-02-03,No,High,34163.02,94,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2035,42.0,88530.0,153490.72,677,12,Hyderabad,Retail,Agent,2021-07-10,No,Medium,8455.42,119,8.6
2036,31.0,205738.0,270989.40,392,8,Mumbai,Corporate,Agent,2025-07-05,Yes,High,34087.69,134,2.6
2037,25.0,211994.0,160507.65,737,8,Kolkata,Retail,Online,2022-10-17,Yes,Low,26518.74,87,1.3
2038,64.0,30105.0,32117.15,794,8,Bangalore,Retail,Agent,2023-08-26,No,Low,20943.11,107,9.3
2039,55.0,248332.0,274980.99,783,6,Chennai,Retail,Branch,2023-08-24,Yes,Low,48511.32,119,3.1

In [42]:
# STEP 9 — FINAL VALIDATION

print("\n========== FINAL VALIDATION ==========")

# No duplicate rows
print("Duplicate rows:")
print(df.duplicated().sum())


# Missing values
print("\nMissing values:")
print(df.isnull().sum())


# Datatypes
print("\nDatatypes:")
print(df.dtypes)


# Numeric columns
print("\nNumeric columns:")
print(df.select_dtypes(include="number").columns)


# City distribution
print("\nCity distribution:")
print(df["Customer_City"].value_counts())


# Segment distribution
print("\nSegment distribution:")
print(df["Customer_Segment"].value_counts())


# Channel distribution
print("\nChannel distribution:")
print(df["Customer_Channel"].value_counts())


# Risk distribution
print("\nRisk Level distribution:")
print(df["Customer_RiskLevel"].value_counts())

========== FINAL VALIDATION ==========
Duplicate rows:
0

Missing values:
Customer_Customer_Customer_Age                   0
Customer_Customer_Customer_AnnualIncome          0
Customer_Customer_Customer_AccountBalance        0
Customer_Customer_Customer_CreditScore           0
Customer_Customer_Customer_Tenure                0
Customer_Customer_Customer_City                 80
Customer_Customer_Customer_Segment               0
Customer_Customer_Customer_Channel               0
Customer_Customer_Customer_CustomerJoinDate      0
Customer_Customer_Customer_Active                0
Customer_Customer_Customer_RiskLevel             0
Customer_Customer_Customer_MonthlySpend          0
Customer_Customer_Customer_Transactions          0
Customer_Customer_Customer_SatisfactionScore     0
dtype: int64

Datatypes:
Customer_Customer_Customer_Age                         float64
Customer_Customer_Customer_AnnualIncome                float64
Customer_Customer_Customer_AccountBalance              float64
Customer_Customer_Customer_CreditScore                   int64
Customer_Customer_Customer_Tenure                        int64
Customer_Customer_Customer_City                            str
Customer_Customer_Customer_Segment                         str
Customer_Customer_Customer_Channel                         str
Customer_Customer_Customer_CustomerJoinDate     datetime64[us]
Customer_Customer_Customer_Active                          str
Customer_Customer_Customer_RiskLevel                       str
Customer_Customer_Customer_MonthlySpend                float64
Customer_Customer_Customer_Transactions                  int64
Customer_Customer_Customer_SatisfactionScore           float64
dtype: object

Numeric columns:
Index(['Customer_Customer_Customer_Age',
       'Customer_Customer_Customer_AnnualIncome',
       'Customer_Customer_Customer_AccountBalance',
       'Customer_Customer_Customer_CreditScore',
       'Customer_Customer_Customer_Tenure',
       'Customer_Customer_Customer_MonthlySpend',
       'Customer_Customer_Customer_Transactions',
       'Customer_Customer_Customer_SatisfactionScore'],
      dtype='str')

City distribution:

KeyError: 'Customer_City'