# 7-Aug-26

# Pandas Challenges

In [4]:
# Challenge 1 – Complete Data Cleaning

import pandas as pd

# Load Dataset
df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Display dataset information
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None

In [5]:
# Find missing values

print(df.isnull().sum())

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [9]:
# Remove duplicate rows

df = df.drop_duplicates()

In [10]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [11]:
# Fill missing values:

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [22]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [23]:
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [14]:
# Rename Columns

df = df.rename(columns={
    "Target": "CustomerStatus",
    "AnnualIncome": "Income"
})

In [15]:
df

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [16]:
# Display first 15 rows

print(df.head(15))

    CustomerID   Age    Income  Spending  CreditScore        Balance  Tenure  \
0        10001  58.0   49184.0      2139          581   97557.565779       2
1        10002  65.0  162964.0      6197          732    6356.540000       1
2        10003  56.0   26956.0     37281          503  143203.920000       8
3        10004  55.0   92926.0       925          463  139627.880000       5
4        10005  66.0  108236.0      7198          394   75985.460000       5
5        10006  69.0   31390.0     48323          770  107245.620000       6
6        10007  58.0  182141.0     24200          891   38457.720000       1
7        10008  67.0   95861.0      5729          538  173296.730000       6
8        10009  41.0   62638.0     24760          663   41901.410000       4
9        10010  22.0  179680.0     42113          475  106827.980000       3
10       10011  44.0  187772.0     45599          870   43923.030000       5
11       10012  69.0  102694.0     26790          574   13237.720000       9
12       10013  59.0  150870.0     26428          769   28574.320000       2
13       10014  52.0   88876.0     49456          898   85686.770000       9
14       10015  26.0  153569.0     32843          393  151156.430000       1

   Geography  Gender    Segment CustomerStatus
0     France    Male        SME           Stay
1        USA    Male        SME          Churn
2     Canada    Male  Corporate           Stay
3        NaN    Male     Retail          Churn
4         UK   Other  Corporate          Churn
5      India   Other  Corporate           Stay
6      India   Other     Retail          Churn
7         UK  Female        SME           Stay
8     France   Other        SME           Stay
9        USA  Female  Corporate          Churn
10     India     NaN     Retail           Stay
11    France  Female     Retail          Churn
12       USA   Other        SME           Stay
13    Canada  Female     Retail           Stay
14       USA   Other     Retail          Churn

In [17]:
# Challenge 2 – Banking Report

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# select only numeric columns

numeric_df = df.select_dtypes(include="number")
print(numeric_df)

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

In [18]:
# Display summary statistics

print(numeric_df.describe())

         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

In [19]:
# Convert Age and CreditScore to float

df["Age"] = df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)

In [20]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [21]:
df["CreditScore"]

0       581.0
1       732.0
2       503.0
3       463.0
4       394.0
        ...
1015    644.0
1016    303.0
1017    813.0
1018    722.0
1019    430.0
Name: CreditScore, Length: 1020, dtype: float64

In [24]:
# Display information again

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(4), int64(3), str(4)
memory usage: 87.8 KB
None

In [25]:
# Challenge 3 – Duplicate Investigation

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Information before removing duplicates

print("Before:")
print(df.info())

Before:
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None

In [26]:
# Count duplicate rows

print("Duplicate Rows:",
df.duplicated().sum())

Duplicate Rows: 20

In [27]:
# Remove duplicates

df = df.drop_duplicates()

In [28]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [29]:
# Information after removing duplicates

print("After:")
print(df.info())

After:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    str
 8   Gender        950 non-null    str
 9   Segment       950 non-null    str
 10  Target        1000 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 86.1 KB
None

In [30]:
# Show the last 20 rows

print(df.tail(20))

     CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
980       10981  41.0      199633.0      8498          847  173390.59       7
981       10982  34.0       98876.0      6414          541   59484.58       2
982       10983  69.0      188933.0     27126          334        NaN       1
983       10984  44.0      107221.0     47514          732  175352.25       1
984       10985  50.0       37397.0     23559          730  120423.19       8
985       10986  62.0       27169.0      3914          488  126031.27      10
986       10987  30.0      184704.0     20524          621  115161.87       1
987       10988  63.0      190178.0      9025          720  158528.46       5
988       10989  26.0       88335.0     11869          635  159905.73       3
989       10990  29.0      123152.0     25228          884   44897.43       0
990       10991  58.0       79954.0      6331          773   39653.24       2
991       10992  45.0           NaN     17549          452   17812.25       5
992       10993  18.0      157845.0     29018          764  165451.49       7
993       10994  31.0       69950.0     17945          594  149288.61       6
994       10995  56.0       76509.0     19044          493   83666.20       6
995       10996  34.0       81731.0     40980          761  181465.65       5
996       10997  47.0       42475.0      1176          780   26640.99       5
997       10998  31.0      120531.0     46929          733  147220.82       4
998       10999  21.0       33661.0     22314          540   94186.48       5
999       11000  63.0       31930.0       851          559  100908.40       6

    Geography  Gender    Segment Target
980    Canada    Male  Corporate   Stay
981    Canada   Other  Corporate   Stay
982    Canada  Female        SME  Churn
983       USA   Other  Corporate  Churn
984    France  Female  Corporate   Stay
985       USA    Male  Corporate  Churn
986       USA    Male        SME  Churn
987       NaN  Female        SME   Stay
988     India  Female  Corporate   Stay
989   Germany   Other        SME  Churn
990     India  Female        SME   Stay
991       USA   Other     Retail  Churn
992     India    Male        SME   Stay
993       USA  Female     Retail   Stay
994       USA    Male  Corporate  Churn
995   Germany   Other        SME   Stay
996    France  Female        SME   Stay
997     India    Male        SME   Stay
998       NaN   Other        SME   Stay
999        UK  Female        NaN   Stay

In [31]:
# Challenge 4 – HR Department

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Rename Columns

df =df.rename(columns={
    "CustomerID": "Employee_ID",
    "Age": "EmployeeAge",
    "Gender": "EmployeeGender",
    "AnnualIncome": "Salary",
    "Target": "PromotionStatus"
})

In [32]:
df

,Employee_ID,EmployeeAge,Salary,Spending,CreditScore,Balance,Tenure,Geography,EmployeeGender,Segment,PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [33]:
# add prefix

df = df.add_prefix("HR_")

In [34]:
df

,HR_Employee_ID,HR_EmployeeAge,HR_Salary,HR_Spending,HR_CreditScore,HR_Balance,HR_Tenure,HR_Geography,HR_EmployeeGender,HR_Segment,HR_PromotionStatus
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [35]:
# Display 10 random records

print(df.sample(10))

     HR_Employee_ID  HR_EmployeeAge  HR_Salary  HR_Spending  HR_CreditScore  \
609           10610            70.0    20314.0        44970             741
275           10276            58.0    81036.0         3940             402
328           10329            23.0   126241.0        25355             686
302           10303            46.0   176705.0        44541             349
509           10510            45.0    55072.0        22961             801
365           10366            29.0   115890.0        21863             501
321           10322            70.0   195168.0         3679             306
113           10114            44.0   107374.0        21540             407
901           10902            26.0   197735.0        36607             419
623           10624            41.0    82719.0        43427             300

     HR_Balance  HR_Tenure HR_Geography HR_EmployeeGender HR_Segment  \
609   104408.85          5        India             Other        SME
275    82660.27          7        India             Other     Retail
328   110540.29          0       France               NaN        SME
302    48946.83          0       Canada            Female     Retail
509    71850.18          3          USA               NaN     Retail
365    91510.08          4       France            Female        SME
321    82478.44         10          USA              Male        SME
113   171546.62          5       Canada             Other  Corporate
901    61616.44          6      Germany              Male  Corporate
623   195129.18          1           UK            Female  Corporate

    HR_PromotionStatus
609               Stay
275              Churn
328              Churn
302              Churn
509               Stay
365               Stay
321              Churn
113              Churn
901              Churn
623              Churn

In [36]:
# Challenge 5 – Finance Cleaning

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Fill missing values
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())

In [37]:
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [38]:
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [39]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [40]:
# Generate descriptive statistics

print(df.describe())

         CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  1020.000000    1020.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112498.242157  25232.615686   602.659804
std      288.022115    15.136428   50925.015723  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   69223.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    57.000000  155570.750000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1020.000000  1020.000000
mean    97523.535666     5.261765
std     54382.357541     3.185330
min       547.600000     0.000000
25%     52145.757500     2.000000
50%     97523.535666     5.000000
75%    142086.700000     8.000000
max    199885.880000    10.000000

In [ ]:
# Challenge 6 – Data Type Audit

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Convert Data types
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Target"] = df["Target"].astype(str)

In [42]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [43]:
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018         NaN
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [44]:
df["Balance"]

0             NaN
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019          NaN
Name: Balance, Length: 1020, dtype: float64

In [45]:
df["Target"]

0        Stay
1       Churn
2        Stay
3       Churn
4       Churn
        ...
1015     Stay
1016    Churn
1017     Stay
1018     Stay
1019    Churn
Name: Target, Length: 1020, dtype: str

In [46]:
# Display Information

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None

In [47]:
# Challenge 7 – Customer Analytics

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Create a new DataFrame 

new_df = df.drop(columns=["Segment","Geography"])
new_df = new_df.drop_duplicates()

In [48]:
new_df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Gender,Target
0,10001,58.0,49184.0,2139,581,NaN,2,Male,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,Male,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Male,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,Male,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Other,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,Female,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,Male,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,Other,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,Female,Stay

In [49]:
# First 10 rows

print(new_df.head(10))

   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5
5       10006  69.0       31390.0     48323          770  107245.62       6
6       10007  58.0      182141.0     24200          891   38457.72       1
7       10008  67.0       95861.0      5729          538  173296.73       6
8       10009  41.0       62638.0     24760          663   41901.41       4
9       10010  22.0      179680.0     42113          475  106827.98       3

   Gender Target
0    Male   Stay
1    Male  Churn
2    Male   Stay
3    Male  Churn
4   Other  Churn
5   Other   Stay
6   Other  Churn
7  Female   Stay
8   Other   Stay
9  Female  Churn

In [50]:
# Dataset information

print(new_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Gender        950 non-null    str
 8   Target        1000 non-null   str
dtypes: float64(3), int64(4), str(2)
memory usage: 70.4 KB
None

In [51]:
# statistical summary

print(new_df.describe())

         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1000.000000  950.000000     950.000000   1000.000000  1000.000000
mean   10500.500000   44.212632  112458.303158  25285.558000   603.088000
std      288.819436   15.524244   52409.868404  14211.735656   176.605486
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10250.750000   30.000000   65922.500000  13213.000000   441.000000
50%    10500.500000   44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000   58.000000  157973.000000  37960.250000   758.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     950.000000  1000.000000
mean    97557.565779     5.241000
std     55845.536430     3.179155
min       547.600000     0.000000
25%     50003.880000     2.000000
50%     95174.625000     5.000000
75%    144198.130000     8.000000
max    199885.880000    10.000000

In [52]:
# Challenge 8 – ML Dataset Preparation

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Remove duplicates

df = df.drop_duplicates()

In [53]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [57]:
# remove Columns

df = df.drop(columns=["CustomerID","Segment"])

KeyError: "['CustomerID', 'Segment'] not found in axis"

In [ ]:
# Fill missing values

df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [58]:
df["Age"]

0      58.0
1      65.0
2      56.0
3      55.0
4      66.0
       ...
995    34.0
996    47.0
997    31.0
998    21.0
999    63.0
Name: Age, Length: 1000, dtype: float64

In [59]:
df["AnnualIncome"]

0       49184.0
1      162964.0
2       26956.0
3       92926.0
4      108236.0
         ...
995     81731.0
996     42475.0
997    120531.0
998     33661.0
999     31930.0
Name: AnnualIncome, Length: 1000, dtype: float64

In [60]:
df["Balance"]

0            NaN
1        6356.54
2      143203.92
3      139627.88
4       75985.46
         ...
995    181465.65
996     26640.99
997    147220.82
998     94186.48
999    100908.40
Name: Balance, Length: 1000, dtype: float64

In [61]:
# Rename Column

df = df.rename(columns={"Target":"Output"})

In [62]:
df

,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Output
0,58.0,49184.0,2139,581,NaN,2,France,Male,Stay
1,65.0,162964.0,6197,732,6356.54,1,USA,Male,Churn
2,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Stay
3,55.0,92926.0,925,463,139627.88,5,NaN,Male,Churn
4,66.0,108236.0,7198,394,75985.46,5,UK,Other,Churn
...,...,...,...,...,...,...,...,...,...
995,34.0,81731.0,40980,761,181465.65,5,Germany,Other,Stay
996,47.0,42475.0,1176,780,26640.99,5,France,Female,Stay
997,31.0,120531.0,46929,733,147220.82,4,India,Male,Stay
998,21.0,33661.0,22314,540,94186.48,5,NaN,Other,Stay
999,63.0,31930.0,851,559,100908.40,6,UK,Female,Stay

In [63]:
# Display

print(df.info())
print(df.head())
print(df.describe())
print(df["Output"].value_counts())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Age           950 non-null    float64
 1   AnnualIncome  950 non-null    float64
 2   Spending      1000 non-null   int64
 3   CreditScore   1000 non-null   int64
 4   Balance       950 non-null    float64
 5   Tenure        1000 non-null   int64
 6   Geography     950 non-null    str
 7   Gender        950 non-null    str
 8   Output        1000 non-null   str
dtypes: float64(3), int64(3), str(3)
memory usage: 70.4 KB
None
    Age  AnnualIncome  Spending  CreditScore    Balance  Tenure Geography  \
0  58.0       49184.0      2139          581        NaN       2    France
1  65.0      162964.0      6197          732    6356.54       1       USA
2  56.0       26956.0     37281          503  143203.92       8    Canada
3  55.0       92926.0       925          463  139627.88       5       NaN
4  66.0      108236.0      7198          394   75985.46       5        UK

  Gender Output
0   Male   Stay
1   Male  Churn
2   Male   Stay
3   Male  Churn
4  Other  Churn
              Age   AnnualIncome      Spending  CreditScore        Balance  \
count  950.000000     950.000000   1000.000000  1000.000000     950.000000
mean    44.212632  112458.303158  25285.558000   603.088000   97557.565779
std     15.524244   52409.868404  14211.735656   176.605486   55845.536430
min     18.000000   20227.000000    537.000000   300.000000     547.600000
25%     30.000000   65922.500000  13213.000000   441.000000   50003.880000
50%     44.000000  112347.500000  24901.000000   606.500000   95174.625000
75%     58.000000  157973.000000  37960.250000   758.250000  144198.130000
max     70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1000.000000
mean      5.241000
std       3.179155
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000
Output
Churn    506
Stay     494
Name: count, dtype: int64

In [1]:
# Challenge 9 – Column Transformation

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

df["NetWorth"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfterRetirement"] = df["Age"] + 20
df["DoubleCreditScore"] = df["CreditScore"] * 2
df["IncomePerMonth"] = df["AnnualIncome"] / 12
print(df.head(15))

    CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0        10001  58.0       49184.0      2139          581        NaN       2
1        10002  65.0      162964.0      6197          732    6356.54       1
2        10003  56.0       26956.0     37281          503  143203.92       8
3        10004  55.0       92926.0       925          463  139627.88       5
4        10005  66.0      108236.0      7198          394   75985.46       5
5        10006  69.0       31390.0     48323          770  107245.62       6
6        10007  58.0      182141.0     24200          891   38457.72       1
7        10008  67.0       95861.0      5729          538  173296.73       6
8        10009  41.0       62638.0     24760          663   41901.41       4
9        10010  22.0      179680.0     42113          475  106827.98       3
10       10011   NaN      187772.0     45599          870   43923.03       5
11       10012  69.0      102694.0     26790          574   13237.72       9
12       10013  59.0      150870.0     26428          769   28574.32       2
13       10014  52.0       88876.0     49456          898   85686.77       9
14       10015  26.0      153569.0     32843          393  151156.43       1

   Geography  Gender    Segment Target   NetWorth  AgeAfterRetirement  \
0     France    Male        SME   Stay        NaN                78.0
1        USA    Male        SME  Churn  169320.54                85.0
2     Canada    Male  Corporate   Stay  170159.92                76.0
3        NaN    Male     Retail  Churn  232553.88                75.0
4         UK   Other  Corporate  Churn  184221.46                86.0
5      India   Other  Corporate   Stay  138635.62                89.0
6      India   Other     Retail  Churn  220598.72                78.0
7         UK  Female        SME   Stay  269157.73                87.0
8     France   Other        SME   Stay  104539.41                61.0
9        USA  Female  Corporate  Churn  286507.98                42.0
10     India     NaN     Retail   Stay  231695.03                 NaN
11    France  Female     Retail  Churn  115931.72                89.0
12       USA   Other        SME   Stay  179444.32                79.0
13    Canada  Female     Retail   Stay  174562.77                72.0
14       USA   Other     Retail  Churn  304725.43                46.0

    DoubleCreditScore  IncomePerMonth
0                1162     4098.666667
1                1464    13580.333333
2                1006     2246.333333
3                 926     7743.833333
4                 788     9019.666667
5                1540     2615.833333
6                1782    15178.416667
7                1076     7988.416667
8                1326     5219.833333
9                 950    14973.333333
10               1740    15647.666667
11               1148     8557.833333
12               1538    12572.500000
13               1796     7406.333333
14                786    12797.416667

In [2]:
# Challenge 10 – Company Report

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

print(df.head())
print(df.tail())
print(df.sample(10))
print(df.info())
print(df.describe())
df = df.rename(columns={"Target":"Customer_Status"})

   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target
0    France   Male        SME   Stay
1       USA   Male        SME  Churn
2    Canada   Male  Corporate   Stay
3       NaN   Male     Retail  Churn
4        UK  Other  Corporate  Churn
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
1015       10450  43.0      173620.0      7121          644   60353.03
1016       10753  25.0       54490.0     13794          303  124512.07
1017       10810  49.0       82062.0     47170          813   53850.09
1018       10267  38.0           NaN     10424          722  138100.05
1019       10059  62.0       97504.0     36833          430        NaN

      Tenure Geography  Gender    Segment Target
1015       2       USA   Other  Corporate   Stay
1016       4     India     NaN  Corporate  Churn
1017       8   Germany  Female     Retail   Stay
1018       6   Germany   Other  Corporate   Stay
1019      10    Canada   Other        NaN  Churn
      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  \
363        10364  29.0       68860.0     42474          742   79116.48
1015       10450  43.0      173620.0      7121          644   60353.03
869        10870  20.0      169072.0      4409          587   27300.30
772        10773  27.0       93520.0      2542          647  196723.75
630        10631  22.0      120315.0     42027          525  135382.60
452        10453  18.0      170165.0     26163          881    6476.55
84         10085  67.0       99058.0     45343          423  159245.44
668        10669  30.0      104054.0      1771          455    9926.41
86         10087  24.0      133645.0     24236          770  141461.73
244        10245  23.0      151746.0     42507          472        NaN

      Tenure Geography  Gender    Segment Target
363        9       USA  Female        SME   Stay
1015       2       USA   Other  Corporate   Stay
869        7    Canada  Female     Retail   Stay
772       10   Germany    Male        SME   Stay
630        3        UK  Female  Corporate   Stay
452        9       NaN   Other     Retail  Churn
84         9     India  Female        SME  Churn
668        8     India    Male     Retail  Churn
86         6       USA   Other        SME   Stay
244        9       USA    Male        SME  Churn
<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None
         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

In [3]:
# Challenge 11 – Missing Value Report

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Total missing values
print(df.isnull().sum())

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [4]:
# Numerical columns

print(df.select_dtypes(include="number").columns)

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure'],
      dtype='str')

In [5]:
# Mean of Balance

print(df["Balance"].mean())

97523.53566563467

In [6]:
# Median of Age

print(df["Age"].median())

44.0

In [7]:
# Fill missing values

df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].mean())
df["Balance"] = df["Balance"].fillna(df["Balance"].median())

In [8]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [9]:
df["AnnualIncome"]

0        49184.000000
1       162964.000000
2        26956.000000
3        92926.000000
4       108236.000000
            ...
1015    173620.000000
1016     54490.000000
1017     82062.000000
1018    112505.928645
1019     97504.000000
Name: AnnualIncome, Length: 1020, dtype: float64

In [10]:
df["Balance"]

0        95100.06
1         6356.54
2       143203.92
3       139627.88
4        75985.46
          ...
1015     60353.03
1016    124512.07
1017     53850.09
1018    138100.05
1019     95100.06
Name: Balance, Length: 1020, dtype: float64

In [11]:
# Display information again

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    str
 8   Gender        968 non-null    str
 9   Segment       969 non-null    str
 10  Target        1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None

In [12]:
# Challenge 12 – Customer Classification

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Count Stay and Churn
print(df["Target"].value_counts())

Target
Churn    515
Stay     505
Name: count, dtype: int64

In [14]:
# Rename

df = df.rename(columns={"Target": "Customer_Class"})

In [15]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Class
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [16]:
# Convert it into string

df["Customer_Class"]= df["Customer_Class"].astype(str)
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             970 non-null    float64
 2   AnnualIncome    967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   int64
 5   Balance         969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    str
 8   Gender          968 non-null    str
 9   Segment         969 non-null    str
 10  Customer_Class  1020 non-null   str
dtypes: float64(3), int64(4), str(4)
memory usage: 87.8 KB
None

In [17]:
# Challenge 13 – Sales Department

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Rename Columns

df = df.rename(columns={
    "Balance":"AccountBalance",
    "AnnualIncome":"Salary",
    "CreditScore":"Score"
})
# Add Prefix

df = df.add_prefix("Sales_")

In [18]:
df

,Sales_CustomerID,Sales_Age,Sales_Salary,Sales_Spending,Sales_Score,Sales_AccountBalance,Sales_Tenure,Sales_Geography,Sales_Gender,Sales_Segment,Sales_Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
1015,10450,43.0,173620.0,7121,644,60353.03,2,USA,Other,Corporate,Stay
1016,10753,25.0,54490.0,13794,303,124512.07,4,India,NaN,Corporate,Churn
1017,10810,49.0,82062.0,47170,813,53850.09,8,Germany,Female,Retail,Stay
1018,10267,38.0,NaN,10424,722,138100.05,6,Germany,Other,Corporate,Stay
1019,10059,62.0,97504.0,36833,430,NaN,10,Canada,Other,NaN,Churn

In [19]:
# Display 20 random rows

print(df.sample(20))

      Sales_CustomerID  Sales_Age  Sales_Salary  Sales_Spending  Sales_Score  \
1018             10267       38.0           NaN           10424          722
110              10111       45.0      104494.0           40064          556
221              10222       36.0       72845.0            3370          504
91               10092       30.0       42442.0           16317          716
872              10873        NaN       93182.0            1450          738
570              10571       39.0       29931.0            6235          375
182              10183       43.0       25467.0           21784          475
206              10207       34.0       33678.0           42520          792
710              10711       32.0      133229.0           19491          703
596              10597       29.0      118739.0           43339          687
439              10440       58.0      162516.0            1779          691
222              10223       70.0      162352.0           31524          559
379              10380        NaN       56499.0           14041          511
1013             10531       64.0       85162.0           32083          654
133              10134       57.0      120281.0           41113          546
119              10120       25.0      189793.0           10590          810
214              10215       58.0      155102.0           38186          547
1009             10499       34.0      166546.0           12497          643
674              10675       67.0       44631.0           34653          513
716              10717       57.0       58225.0           29366          345

      Sales_AccountBalance  Sales_Tenure Sales_Geography Sales_Gender  \
1018             138100.05             6         Germany        Other
110                5172.98             3          France        Other
221              177158.08             5              UK        Other
91                97715.57             3          France       Female
872              147235.77             3             USA       Female
570               10853.61             4         Germany         Male
182                    NaN             9             NaN        Other
206                    NaN             8           India        Other
710               29602.48             5           India       Female
596               73059.36            10             NaN        Other
439              156383.15             5          Canada        Other
222                7324.15            10             USA       Female
379              161088.10             9              UK        Other
1013             132742.13            10          Canada         Male
133               99533.45             9             USA         Male
119              186530.61             4         Germany        Other
214              143708.87             4          Canada         Male
1009             130886.93             3              UK         Male
674               94565.11            10              UK       Female
716              184842.64             3             USA        Other

     Sales_Segment Sales_Target
1018     Corporate         Stay
110            SME        Churn
221      Corporate         Stay
91             SME         Stay
872      Corporate         Stay
570            NaN        Churn
182      Corporate        Churn
206            SME         Stay
710            SME         Stay
596      Corporate         Stay
439      Corporate         Stay
222      Corporate        Churn
379      Corporate         Stay
1013           SME         Stay
133      Corporate         Stay
119      Corporate         Stay
214            SME         Stay
1009           SME         Stay
674            NaN         Stay
716      Corporate        Churn

In [20]:
# Challenge 14 – Interview Challenge

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Remove Duplicates

df.drop_duplicates(inplace=True)

In [21]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [22]:
# rename Target

df.rename(columns={"Target":"Customer_Status"},inplace=True)

In [24]:
df.rename

<bound method DataFrame.rename of      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0         10001  58.0       49184.0      2139          581        NaN       2
1         10002  65.0      162964.0      6197          732    6356.54       1
2         10003  56.0       26956.0     37281          503  143203.92       8
3         10004  55.0       92926.0       925          463  139627.88       5
4         10005  66.0      108236.0      7198          394   75985.46       5
..          ...   ...           ...       ...          ...        ...     ...
995       10996  34.0       81731.0     40980          761  181465.65       5
996       10997  47.0       42475.0      1176          780   26640.99       5
997       10998  31.0      120531.0     46929          733  147220.82       4
998       10999  21.0       33661.0     22314          540   94186.48       5
999       11000  63.0       31930.0       851          559  100908.40       6

    Geography  Gender    Segment Customer_Status
0      France    Male        SME            Stay
1         USA    Male        SME           Churn
2      Canada    Male  Corporate            Stay
3         NaN    Male     Retail           Churn
4          UK   Other  Corporate           Churn
..        ...     ...        ...             ...
995   Germany   Other        SME            Stay
996    France  Female        SME            Stay
997     India    Male        SME            Stay
998       NaN   Other        SME            Stay
999        UK  Female        NaN            Stay

[1000 rows x 11 columns]>

In [28]:
# convert Balance to float

df["Balance"] = df["Balance"].astype(float)

In [29]:
df["Balance"]

0            NaN
1        6356.54
2      143203.92
3      139627.88
4       75985.46
         ...
995    181465.65
996     26640.99
997    147220.82
998     94186.48
999    100908.40
Name: Balance, Length: 1000, dtype: float64

In [31]:
# Display Summary

print(df.describe())

         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1000.000000  950.000000     950.000000   1000.000000  1000.000000
mean   10500.500000   44.212632  112458.303158  25285.558000   603.088000
std      288.819436   15.524244   52409.868404  14211.735656   176.605486
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10250.750000   30.000000   65922.500000  13213.000000   441.000000
50%    10500.500000   44.000000  112347.500000  24901.000000   606.500000
75%    10750.250000   58.000000  157973.000000  37960.250000   758.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     950.000000  1000.000000
mean    97557.565779     5.241000
std     55845.536430     3.179155
min       547.600000     0.000000
25%     50003.880000     2.000000
50%     95174.625000     5.000000
75%    144198.130000     8.000000
max    199885.880000    10.000000

In [32]:
# Challenge 15 – Data Engineer Task

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Create another DataFrame containing only numeric columns

numeric_df = df.select_dtypes(include="number")

In [33]:
numeric_df

      CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0          10001  58.0       49184.0      2139          581        NaN       2
1          10002  65.0      162964.0      6197          732    6356.54       1
2          10003  56.0       26956.0     37281          503  143203.92       8
3          10004  55.0       92926.0       925          463  139627.88       5
4          10005  66.0      108236.0      7198          394   75985.46       5
...          ...   ...           ...       ...          ...        ...     ...
1015       10450  43.0      173620.0      7121          644   60353.03       2
1016       10753  25.0       54490.0     13794          303  124512.07       4
1017       10810  49.0       82062.0     47170          813   53850.09       8
1018       10267  38.0           NaN     10424          722  138100.05       6
1019       10059  62.0       97504.0     36833          430        NaN      10

[1020 rows x 7 columns]

In [34]:
# Drop columns

numeric_df = numeric_df.drop(columns=["CustomerID"])

In [35]:
numeric_df

       Age  AnnualIncome  Spending  CreditScore    Balance  Tenure
0     58.0       49184.0      2139          581        NaN       2
1     65.0      162964.0      6197          732    6356.54       1
2     56.0       26956.0     37281          503  143203.92       8
3     55.0       92926.0       925          463  139627.88       5
4     66.0      108236.0      7198          394   75985.46       5
...    ...           ...       ...          ...        ...     ...
1015  43.0      173620.0      7121          644   60353.03       2
1016  25.0       54490.0     13794          303  124512.07       4
1017  49.0       82062.0     47170          813   53850.09       8
1018  38.0           NaN     10424          722  138100.05       6
1019  62.0       97504.0     36833          430        NaN      10

[1020 rows x 6 columns]

In [36]:
# Display Summary

print(numeric_df.describe())

              Age   AnnualIncome      Spending  CreditScore        Balance  \
count  970.000000     967.000000   1020.000000  1020.000000     969.000000
mean    44.249485  112505.928645  25232.615686   602.659804   97523.535666
std     15.521935   52303.362541  14219.393105   176.560690   55796.562543
min     18.000000   20227.000000    537.000000   300.000000     547.600000
25%     30.250000   66149.000000  13134.750000   440.750000   50077.860000
50%     44.000000  112358.000000  24798.000000   607.000000   95100.060000
75%     58.000000  158000.500000  37956.000000   757.250000  143947.810000
max     70.000000  199967.000000  49995.000000   900.000000  199885.880000

            Tenure
count  1020.000000
mean      5.261765
std       3.185330
min       0.000000
25%       2.000000
50%       5.000000
75%       8.000000
max      10.000000

In [1]:
# Challenge 16 – Mixed Cleaning

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Remove Duplicates

df = df.drop_duplicates()

In [2]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [3]:
# Fill missing values

df["Age"] = df["Age"].fillna(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [4]:
df["Age"]

0      58.0
1      65.0
2      56.0
3      55.0
4      66.0
       ...
995    34.0
996    47.0
997    31.0
998    21.0
999    63.0
Name: Age, Length: 1000, dtype: float64

In [5]:
df["Balance"]

0       97557.565779
1        6356.540000
2      143203.920000
3      139627.880000
4       75985.460000
           ...
995    181465.650000
996     26640.990000
997    147220.820000
998     94186.480000
999    100908.400000
Name: Balance, Length: 1000, dtype: float64

In [6]:
# convert Datatype

df["Age"] = df["Age"].astype(int)

In [7]:
df["Age"]

0      58
1      65
2      56
3      55
4      66
       ..
995    34
996    47
997    31
998    21
999    63
Name: Age, Length: 1000, dtype: int64

In [8]:
# Rename Target

df = df.rename(columns={"Target":"Customer_Status"})

In [9]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [10]:
# Display first 5 rows

print(df.head(5))

   CustomerID  Age  AnnualIncome  Spending  CreditScore        Balance  \
0       10001   58       49184.0      2139          581   97557.565779
1       10002   65      162964.0      6197          732    6356.540000
2       10003   56       26956.0     37281          503  143203.920000
3       10004   55       92926.0       925          463  139627.880000
4       10005   66      108236.0      7198          394   75985.460000

   Tenure Geography Gender    Segment Customer_Status
0       2    France   Male        SME            Stay
1       1       USA   Male        SME           Churn
2       8    Canada   Male  Corporate            Stay
3       5       NaN   Male     Retail           Churn
4       5        UK  Other  Corporate           Churn

In [11]:
# Display Information

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1000 non-null   int64
 1   Age              1000 non-null   int64
 2   AnnualIncome     950 non-null    float64
 3   Spending         1000 non-null   int64
 4   CreditScore      1000 non-null   int64
 5   Balance          1000 non-null   float64
 6   Tenure           1000 non-null   int64
 7   Geography        950 non-null    str
 8   Gender           950 non-null    str
 9   Segment          950 non-null    str
 10  Customer_Status  1000 non-null   str
dtypes: float64(2), int64(5), str(4)
memory usage: 86.1 KB
None

In [12]:
# Challenge 17 – Real Company Dataset

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Remove Duplicates

df = df.drop_duplicates()

In [13]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [14]:
# Fill missing values

df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [15]:
df["Age"]

0      58.0
1      65.0
2      56.0
3      55.0
4      66.0
       ...
995    34.0
996    47.0
997    31.0
998    21.0
999    63.0
Name: Age, Length: 1000, dtype: float64

In [16]:
df["AnnualIncome"]

0       49184.0
1      162964.0
2       26956.0
3       92926.0
4      108236.0
         ...
995     81731.0
996     42475.0
997    120531.0
998     33661.0
999     31930.0
Name: AnnualIncome, Length: 1000, dtype: float64

In [17]:
df["Balance"]

0       97557.565779
1        6356.540000
2      143203.920000
3      139627.880000
4       75985.460000
           ...
995    181465.650000
996     26640.990000
997    147220.820000
998     94186.480000
999    100908.400000
Name: Balance, Length: 1000, dtype: float64

In [20]:
# Rename all business columns

df = df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Annual_Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
})

In [21]:
df

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [22]:
# Add company prefix

df = df.add_prefix("Company_")

In [23]:
df

,Company_Customer_ID,Company_Age,Company_Annual_Income,Company_Spending,Company_Credit_Score,Company_Balance,Company_Tenure,Company_Geography,Company_Gender,Company_Segment,Company_Customer_Status
0,10001,58.0,49184.0,2139,581,97557.565779,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.650000,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.990000,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.820000,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.480000,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.400000,6,UK,Female,NaN,Stay

In [24]:
# Display summary

print(df.describe())

       Company_Customer_ID  Company_Age  Company_Annual_Income  \
count          1000.000000  1000.000000            1000.000000
mean          10500.500000    44.202000          112452.763000
std             288.819436    15.130834           51081.480963
min           10001.000000    18.000000           20227.000000
25%           10250.750000    31.000000           68437.250000
50%           10500.500000    44.000000          112347.500000
75%           10750.250000    57.000000          155570.750000
max           11000.000000    70.000000          199967.000000

       Company_Spending  Company_Credit_Score  Company_Balance  Company_Tenure
count       1000.000000           1000.000000      1000.000000     1000.000000
mean       25285.558000            603.088000     97557.565779        5.241000
std        14211.735656            176.605486     54430.062006        3.179155
min          537.000000            300.000000       547.600000        0.000000
25%        13213.000000            441.000000     52074.240000        2.000000
50%        24901.000000            606.500000     97557.565779        5.000000
75%        37960.250000            758.250000    142297.910000        8.000000
max        49995.000000            900.000000    199885.880000       10.000000

In [25]:
# Display target counts

print(df["Company_Customer_Status"].value_counts())

Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [26]:
# Challenge 18 – Customer Summary

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# Calculate Statistics

mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
mean_age = df["Age"].mean()
median_annualincome = df["AnnualIncome"].median()

print("Mean Balance:", "mean_balance")
print("Median Balance:", "median_balance")
print("Mean Age:", "mean_age")
print("Median AnnualIncome:", "median_income")

Mean Balance: mean_balance
Median Balance: median_balance
Mean Age: mean_age
Median AnnualIncome: median_income

In [33]:
# fill missing values

df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)

In [34]:
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [35]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [36]:
print(df.head())

   CustomerID   Age  AnnualIncome  Spending  CreditScore        Balance  \
0       10001  58.0       49184.0      2139          581   97523.535666
1       10002  65.0      162964.0      6197          732    6356.540000
2       10003  56.0       26956.0     37281          503  143203.920000
3       10004  55.0       92926.0       925          463  139627.880000
4       10005  66.0      108236.0      7198          394   75985.460000

   Tenure Geography Gender    Segment Target
0       2    France   Male        SME   Stay
1       1       USA   Male        SME  Churn
2       8    Canada   Male  Corporate   Stay
3       5       NaN   Male     Retail  Churn
4       5        UK  Other  Corporate  Churn

In [37]:
# Challenge 19 – Transformation Challenge

import pandas as pd

df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000
df["Balance_in_Lakhs"] = df["Balance"] / 100000
df["SeniorCitizen"] = df["Age"] + 0
df["HighCreditScore"] = df["CreditScore"] * 1

print(df.head())

   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target  Income_in_Lakhs  Balance_in_Lakhs  \
0    France   Male        SME   Stay          0.49184               NaN
1       USA   Male        SME  Churn          1.62964          0.063565
2    Canada   Male  Corporate   Stay          0.26956          1.432039
3       NaN   Male     Retail  Churn          0.92926          1.396279
4        UK  Other  Corporate  Churn          1.08236          0.759855

   SeniorCitizen  HighCreditScore
0           58.0              581
1           65.0              732
2           56.0              503
3           55.0              463
4           66.0              394

In [1]:
# Challenge 20 – Final Interview Project

import pandas as pd

# Load dataset
df = pd.read_csv("C:\\Users\\91965\\OneDrive\\Desktop\\.ipynb_checkpoints\\Data Science Course\\Task_dataset.Csv")

# check information

print("Before Cleaning:")
print(df.head())

Before Cleaning:
   CustomerID   Age  AnnualIncome  Spending  CreditScore    Balance  Tenure  \
0       10001  58.0       49184.0      2139          581        NaN       2
1       10002  65.0      162964.0      6197          732    6356.54       1
2       10003  56.0       26956.0     37281          503  143203.92       8
3       10004  55.0       92926.0       925          463  139627.88       5
4       10005  66.0      108236.0      7198          394   75985.46       5

  Geography Gender    Segment Target
0    France   Male        SME   Stay
1       USA   Male        SME  Churn
2    Canada   Male  Corporate   Stay
3       NaN   Male     Retail  Churn
4        UK  Other  Corporate  Churn

In [39]:
# Find missing values

print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [40]:
# Remove duplicates

df = df.drop_duplicates()

In [41]:
df

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [42]:
# Rename

df = df.rename(columns={
    "CustomerID" : "Customer_ID",
    "AnnualIncome" : "Annual_Income",
    "CreditScore" : "Credit_Score",
    "Target" : "Customer_Status"
})

In [43]:
df

,Customer_ID,Age,Annual_Income,Spending,Credit_Score,Balance,Tenure,Geography,Gender,Segment,Customer_Status
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn
...,...,...,...,...,...,...,...,...,...,...,...
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [5]:
# fill missing values

df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())

In [6]:
df["Age"]

0       58.0
1       65.0
2       56.0
3       55.0
4       66.0
        ...
1015    43.0
1016    25.0
1017    49.0
1018    38.0
1019    62.0
Name: Age, Length: 1020, dtype: float64

In [7]:
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [8]:
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [9]:
# Convert Datatypes

df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)

In [10]:
df["Age"]

0       58
1       65
2       56
3       55
4       66
        ..
1015    43
1016    25
1017    49
1018    38
1019    62
Name: Age, Length: 1020, dtype: int64

In [11]:
df["AnnualIncome"]

0        49184.0
1       162964.0
2        26956.0
3        92926.0
4       108236.0
          ...
1015    173620.0
1016     54490.0
1017     82062.0
1018    112358.0
1019     97504.0
Name: AnnualIncome, Length: 1020, dtype: float64

In [12]:
df["Balance"]

0        97523.535666
1         6356.540000
2       143203.920000
3       139627.880000
4        75985.460000
            ...
1015     60353.030000
1016    124512.070000
1017     53850.090000
1018    138100.050000
1019     97523.535666
Name: Balance, Length: 1020, dtype: float64

In [17]:
# Create new columns

df["TotalMoney"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["AnnualIncome"] / 12
df["CreditScoreDouble"] = df["CreditScore"] * 2

In [18]:
df["TotalMoney"]

0       146707.535666
1       169320.540000
2       170159.920000
3       232553.880000
4       184221.460000
            ...
1015    233973.030000
1016    179002.070000
1017    135912.090000
1018    250458.050000
1019    195027.535666
Name: TotalMoney, Length: 1020, dtype: float64

In [19]:
df["AgeAfter5Years"]

0       63
1       70
2       61
3       60
4       71
        ..
1015    48
1016    30
1017    54
1018    43
1019    67
Name: AgeAfter5Years, Length: 1020, dtype: int64

In [20]:
df["MonthlyIncome"]

0        4098.666667
1       13580.333333
2        2246.333333
3        7743.833333
4        9019.666667
            ...
1015    14468.333333
1016     4540.833333
1017     6838.500000
1018     9363.166667
1019     8125.333333
Name: MonthlyIncome, Length: 1020, dtype: float64

In [21]:
df["CreditScoreDouble"]

0       1162
1       1464
2       1006
3        926
4        788
        ...
1015    1288
1016     606
1017    1626
1018    1444
1019     860
Name: CreditScoreDouble, Length: 1020, dtype: int64

In [ ]:
#